import AllProduct from "@/components/AllProduct";

const getDataBrand = async () => {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_API_URL}/brands?populate=*`,
    // "https://tokobangunan-057n.onrender.com/api/brands?populate=*",
    {
      cache: "no-store",
      // headers: {
      //   Authorization: "bearer " + process.env.NEXT_PUBLIC_API_TOKEN,
      // },
    }
  );

  if (!res.ok) {
    throw new Error("Failed!");
  }

  return res.json();
};
const getDataCategory = async () => {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_API_URL}/categories?populate=*`,

    // "https://tokobangunan-057n.onrender.com/api/categories?populate=*",
    {
      cache: "no-store",
      // headers: {
      //   Authorization: "bearer " + process.env.NEXT_PUBLIC_API_TOKEN,
      // },
    }
  );

  if (!res.ok) {
    throw new Error("Failed!");
  }

  return res.json();
};

export const metadata = {
  title: "Products Mega Utama",
  description: "Generated by create next app",
};

const Products = async () => {
  // const dataProduct = getDataProduct();
  const dataBrand = getDataBrand();
  const dataCategory = getDataCategory();

  const [brand, category] = await Promise.all([dataBrand, dataCategory]);

  return (
    <div className="grid container mx-auto min-h-screen  bg-neutral-50">
      <AllProduct category={category} brand={brand} />
    </div>
  );
};

export default Products;
